version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    parallelism: 3
    resource_class: large
    working_directory: ~/monero-stratum
    branches:
      only:
        - aeon
    steps:
      - run: |
          apt-get -qq update
          apt-get install -y -qq libboost-all-dev golang curl cmake build-essential libssl-dev git-core libzmq3-dev
      - restore_cache:
          keys:
            - v1-aeon-{{ arch }}-v0.12.0.0.tar.gz
      - run:
          command: |
            git clone --recursive --branch v0.12.0.0 https://github.com/aeonix/aeon.git ~/aeon-0.12.0.0
            pushd ~/aeon-0.12.0.0 && cmake -DBUILD_SHARED_LIBS=1 . && make && popd
      - save_cache:
          key: v1-aeon-{{ arch }}-v0.12.0.0.tar.gz
          paths:
            - ~/aeon-0.12.0.0
      - checkout
      - run:
          name: Compile
          environment:
            - AEON_DIR: "~/aeon-0.12.0.0"
          command: |
            cmake .
            make
      - run:
          name: Test
          command: build/env.sh go test -v ./...
