version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    parallelism: 3
    resource_class: large
    working_directory: ~/monero-stratum
    branches:
      only:
        - master
    steps:
      - run: |
          apt-get -qq update
          apt-get install -y -qq libboost-all-dev golang curl cmake build-essential libssl-dev git-core
      - restore_cache:
          keys:
            - v1-aeon-{{ arch }}-v0.9.14.0.tar.gz
      - run:
          environment:
            - CXXFLAGS: "-fPIC"
            - CFLAGS: "-fPIC"
          command: |
            curl -L -o ~/v0.9.14.0.tar.gz https://github.com/aeonix/aeon/archive/v0.9.14.0.tar.gz
            tar xzvf ~/v0.9.14.0.tar.gz -C ~/
            pushd ~/aeon-0.9.14.0 && make && popd
      - save_cache:
          key: v1-aeon-{{ arch }}-v0.9.14.0.tar.gz
          paths:
            - ~/aeon-0.9.14.0
      - checkout
      - run:
          name: Compile
          environment:
            - AEON_DIR: "~/aeon-0.9.14.0"
          command: |
            cmake .
            make
      - run:
          name: Test
          command: build/env.sh go test -v ./...
